## LATITUDE AND LONGITUDE OF TORONTO'S POSTAL CODES

#### Loading csv file with Postal codes, Boroughs and Neighborhoods from Toronto

In [1]:
import pandas as pd

df_tor_2 = pd.read_csv("df_tor.csv")

print(df_tor_2.shape)
df_tor_2.head()

(103, 3)

  PostalCode      Borough                            Neighborhood
0        M1B  Scarborough                          Rouge, Malvern
1        M1C  Scarborough  Highland Creek, Rouge Hill, Port Union
2        M1E  Scarborough       Guildwood, Morningside, West Hill
3        M1G  Scarborough                                  Woburn
4        M1H  Scarborough                               Cedarbrae

### Loading coordinates of Toronto's Postal codes from csv file

In [3]:
coord_tor = pd.read_csv("Geospatial_Coordinates.csv")

coord_tor.head()

  Postal Code   Latitude  Longitude
0         M1B  43.806686 -79.194353
1         M1C  43.784535 -79.160497
2         M1E  43.763573 -79.188711
3         M1G  43.770992 -79.216917
4         M1H  43.773136 -79.239476

### Renaming Postal Code column

In [4]:
coord_tor.rename({'Postal Code': 'PostalCode'}, axis=1, inplace=True)

coord_tor.head(2)

  PostalCode   Latitude  Longitude
0        M1B  43.806686 -79.194353
1        M1C  43.784535 -79.160497

## MERGING THE DATAFRAMES
We use the PostalCode column to merge the two Dataframes

In [5]:
df_tor_f = df_tor_2.merge(coord_tor, on="PostalCode", how="left")
df_tor_f.head()

,PostalCode,Borough,Neighborhood,Latitude,Longitude
0,M1B,Scarborough,"Rouge, Malvern",43.806686,-79.194353
1,M1C,Scarborough,"Highland Creek, Rouge Hill, Port Union",43.784535,-79.160497
2,M1E,Scarborough,"Guildwood, Morningside, West Hill",43.763573,-79.188711
3,M1G,Scarborough,Woburn,43.770992,-79.216917
4,M1H,Scarborough,Cedarbrae,43.773136,-79.239476

## DATAFRAME TEST

creating of the required df in the question

In [9]:
# create a new test dataframe
columns = ["PostalCode", "Borough", "Neighborhood"]
df_quest_2 = pd.DataFrame(columns=columns)

rows = ["M5G", "M2H", "M4B", "M1J", "M4G", "M4M", "M1R", "M9V", "M9L", "M5V", "M1B", "M5A"]

for code in rows:
    df_quest_2 = df_quest_2.append(df_tor_f[df_tor_f["PostalCode"]==code], ignore_index=True,sort=False)
    
df_quest_2

,PostalCode,Borough,Neighborhood,Latitude,Longitude
0,M5G,Downtown Toronto,Central Bay Street,43.657952,-79.387383
1,M2H,North York,Hillcrest Village,43.803762,-79.363452
2,M4B,East York,"Woodbine Gardens, Parkview Hill",43.706397,-79.309937
3,M1J,Scarborough,Scarborough Village,43.744734,-79.239476
4,M4G,East York,Leaside,43.709060,-79.363452
5,M4M,East Toronto,Studio District,43.659526,-79.340923
6,M1R,Scarborough,"Maryvale, Wexford",43.750072,-79.295849
7,M9V,Etobicoke,"Albion Gardens, Beaumond Heights, Humbergate, ...",43.739416,-79.588437
8,M9L,North York,Humber Summit,43.756303,-79.565963
9,M5V,Downtown Toronto,"CN Tower, Bathurst Quay, Island airport, Harbo...",43.628947,-79.394420
10,M1B,Scarborough,"Rouge, Malvern",43.806686,-79.194353
11,M5A,Downtown Toronto,Harbourfront,43.654260,-79.360636